meta_product_name: "Swish"
meta_title: "Swish - Boomshakalaka"
meta_description: "Relevant description"
meta_image: "basketballsocialmetaimage.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
